"""
Django settings for project.

Generated by 'django-admin startproject' using Django 5.0.6.
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# ===========================
# Load Environment Variables
# ===========================
load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

# ===========================
# SECURITY SETTINGS
# ===========================
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-default-key')

# ✅ DEBUG should be False in production
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# ✅ Allowed domains
# Add your Render backend, Netlify frontend, and local development
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "electricity-backend.onrender.com",      # Backend Render domain
    "electricity-frontend.netlify.app"       # Frontend Netlify domain
]

# ===========================
# INSTALLED APPS
# ===========================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Your Django apps
    'app',

    # For handling CORS
    'corsheaders',
]

# ===========================
# MIDDLEWARE
# ===========================
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    # Whitenoise for static file serving in production
    "whitenoise.middleware.WhiteNoiseMiddleware",

    # CORS middleware should be high in the list
    "corsheaders.middleware.CorsMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# ===========================
# URL & WSGI
# ===========================
ROOT_URLCONF = 'project.urls'
WSGI_APPLICATION = 'project.wsgi.application'

# ===========================
# TEMPLATES
# ===========================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        # ✅ Only needed if Django serves React build directly
        'DIRS': [BASE_DIR / "build"],

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ===========================
# DATABASE
# ===========================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ===========================
# PASSWORD VALIDATION
# ===========================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ===========================
# INTERNATIONALIZATION
# ===========================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ===========================
# STATIC FILES
# ===========================
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"  # Where collectstatic stores files

# Whitenoise compression
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# If React's build folder needs to be included in Django static files
# STATICFILES_DIRS = [BASE_DIR / "build" / "static"]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ===========================
# CORS SETTINGS
# ===========================
# ⚠️ IMPORTANT:
# Do NOT include trailing slash at the end of domains in CORS_ALLOWED_ORIGINS

CORS_ALLOWED_ORIGINS = [
    "https://electricity-frontend.netlify.app",  # Netlify frontend
    "http://localhost:3000",                     # Local React dev server
]

# For debugging only, if CORS issues persist:
# CORS_ALLOW_ALL_ORIGINS = True
